/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import Componentes.Table;
import DAO.ProdutoDAO;
import DTO.Produto;
import com.raven.cell.CellAction;
import java.awt.Color;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.standard.Media;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author flavi
 */
public class Content extends javax.swing.JFrame {

    ProdutoDAO produtoDAO = new ProdutoDAO();

    /**
     * Creates new form Content
     */
    private Menu menu;

    public Content(Menu controle) {
        this.menu = controle;
        initComponents();
        TabelaProduto.addTableStyle(jScrollPane2);
        ListarValores();

    }

    public void atualizarTabela() {
        try {
            ListarValoresPeloNome("'" + txtPesquisa.getText() + "%'");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Atualizar tabela" + e);
        }
    } // fim do metodo

    public void ListarValores() {
        try {
            DefaultTableModel model = (DefaultTableModel) TabelaProduto.getModel();
            model.setNumRows(0);

            ArrayList<Produto> lista = produtoDAO.listarProduto();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId(),
                    lista.get(num).getNome(),
                    lista.get(num).getData_cadastro(),
                    lista.get(num).getPreco_venda(),
                    lista.get(num).getPreco_compra(),
                    lista.get(num).getQtd_estoque(),
                    lista.get(num).getFator(),
                    lista.get(num).getCodigo_barra(),});

            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ListarValores" + erro);
        }
    }

    public void ListarValoresPeloNome(String nome) {
        try {

            DefaultTableModel model = (DefaultTableModel) TabelaProduto.getModel();

            model.setNumRows(0);

            ArrayList<Produto> lista = produtoDAO.listarProdutoNome(nome);

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId(),
                    lista.get(num).getNome(),
                    lista.get(num).getData_cadastro(),
                    lista.get(num).getPreco_venda(),
                    lista.get(num).getPreco_compra(),
                    lista.get(num).getQtd_estoque(),
                    lista.get(num).getFator(),
                    lista.get(num).getCodigo_barra(),});

            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ListarValores" + erro);
        }
    }

    public JPanel getFondo() {
        return conteudo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        curveChart1 = new com.raven.chart.CurveChart();
        conteudo = new javax.swing.JPanel();
        pnlPesquisa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnCadastrar = new Componentes.MyButton();
        pnlPesquisa1 = new javax.swing.JPanel();
        myButton2 = new Componentes.MyButton();
        myButton3 = new Componentes.MyButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaProduto = new Componentes.Table();
        btnEditar = new Componentes.MyButton();
        btnDeletar = new Componentes.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        conteudo.setBackground(new java.awt.Color(51, 51, 51));

        pnlPesquisa.setBackground(new java.awt.Color(61, 61, 61));
        pnlPesquisa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        pnlPesquisa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        pnlPesquisa.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 46, 38));

        txtPesquisa.setBackground(new java.awt.Color(102, 102, 102));
        txtPesquisa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        txtPesquisa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtPesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisaFocusGained(evt);
            }
        });
        txtPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPesquisaMouseExited(evt);
            }
        });
        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });
        pnlPesquisa.add(txtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 600, 40));

        btnCadastrar.setBackground(new java.awt.Color(102, 102, 102));
        btnCadastrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-plus-math-16.png"))); // NOI18N
        btnCadastrar.setText(" CADASTRAR");
        btnCadastrar.setBorderColor(new java.awt.Color(102, 102, 102));
        btnCadastrar.setColor(new java.awt.Color(102, 102, 102));
        btnCadastrar.setColorClick(new java.awt.Color(51, 51, 51));
        btnCadastrar.setColorOver(new java.awt.Color(102, 102, 102));
        btnCadastrar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnCadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCadastrar.setVerifyInputWhenFocusTarget(false);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        pnlPesquisa1.setBackground(new java.awt.Color(61, 61, 61));
        pnlPesquisa1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        pnlPesquisa1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myButton2.setBackground(new java.awt.Color(102, 102, 102));
        myButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        myButton2.setForeground(new java.awt.Color(255, 255, 255));
        myButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-impressão-16.png"))); // NOI18N
        myButton2.setText("   IMPRIMIR ");
        myButton2.setBorderColor(new java.awt.Color(102, 102, 102));
        myButton2.setColor(new java.awt.Color(102, 102, 102));
        myButton2.setColorClick(new java.awt.Color(81, 81, 81));
        myButton2.setColorOver(new java.awt.Color(102, 102, 102));
        myButton2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        myButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        myButton2.setVerifyInputWhenFocusTarget(false);
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });
        pnlPesquisa1.add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 130, 40));

        myButton3.setBackground(new java.awt.Color(51, 51, 51));
        myButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        myButton3.setForeground(new java.awt.Color(255, 255, 255));
        myButton3.setText("FECHAR");
        myButton3.setBorderColor(new java.awt.Color(51, 51, 51));
        myButton3.setColor(new java.awt.Color(51, 51, 51));
        myButton3.setColorClick(new java.awt.Color(81, 81, 81));
        myButton3.setColorOver(new java.awt.Color(51, 51, 51));
        myButton3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        myButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        myButton3.setVerifyInputWhenFocusTarget(false);
        myButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton3ActionPerformed(evt);
            }
        });
        pnlPesquisa1.add(myButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 130, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Clicke no Botão de \"CADASTRAR\" para inserir um novo produto...");
        pnlPesquisa1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 450, -1));

        TabelaProduto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        TabelaProduto.setForeground(new java.awt.Color(255, 255, 255));
        TabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Data Cadastro", "Preço Venda", "Preço Compra", "Quantidade", "Fator Lucro", "Codigo Barra"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaProduto.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jScrollPane2.setViewportView(TabelaProduto);
        if (TabelaProduto.getColumnModel().getColumnCount() > 0) {
            TabelaProduto.getColumnModel().getColumn(0).setMinWidth(60);
            TabelaProduto.getColumnModel().getColumn(0).setPreferredWidth(60);
            TabelaProduto.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        btnEditar.setBackground(new java.awt.Color(61, 61, 61));
        btnEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnEditar.setForeground(new java.awt.Color(142, 171, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/edit.png"))); // NOI18N
        btnEditar.setText("EDITAR       ");
        btnEditar.setBorderColor(new java.awt.Color(61, 61, 61));
        btnEditar.setColor(new java.awt.Color(61, 61, 61));
        btnEditar.setColorClick(new java.awt.Color(81, 81, 81));
        btnEditar.setColorOver(new java.awt.Color(61, 61, 61));
        btnEditar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnEditar.setVerifyInputWhenFocusTarget(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnDeletar.setBackground(new java.awt.Color(61, 61, 61));
        btnDeletar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnDeletar.setForeground(new java.awt.Color(255, 153, 153));
        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/delete.png"))); // NOI18N
        btnDeletar.setText("DELETAR    ");
        btnDeletar.setBorderColor(new java.awt.Color(61, 61, 61));
        btnDeletar.setColor(new java.awt.Color(61, 61, 61));
        btnDeletar.setColorClick(new java.awt.Color(81, 81, 81));
        btnDeletar.setColorOver(new java.awt.Color(61, 61, 61));
        btnDeletar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnDeletar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnDeletar.setVerifyInputWhenFocusTarget(false);
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout conteudoLayout = new javax.swing.GroupLayout(conteudo);
        conteudo.setLayout(conteudoLayout);
        conteudoLayout.setHorizontalGroup(
            conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conteudoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlPesquisa1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, conteudoLayout.createSequentialGroup()
                        .addGroup(conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGroup(conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(15, 15, 15))
        );
        conteudoLayout.setVerticalGroup(
            conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conteudoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(conteudoLayout.createSequentialGroup()
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void txtPesquisaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisaMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_txtPesquisaMouseExited

    private void txtPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_txtPesquisaFocusGained

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
        // TODO add your handling code here:
        conteudo.removeAll();
        conteudo.revalidate();
        conteudo.repaint();
    }//GEN-LAST:event_myButton3ActionPerformed
    public void abrirMDI(JPanel panel) {
        panel.setSize(845, 557);
        panel.setLocation(0, 0);

        conteudo.removeAll();
        conteudo.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        conteudo.revalidate();
        conteudo.repaint();
    }
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        Registros panel = new Registros(menu);

        menu.abrirMDI(panel.getFondo());
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if (TabelaProduto.getSelectedRowCount() >= 1) {
            String Codigo = TabelaProduto.getValueAt(TabelaProduto.getSelectedRow(), 0).toString();
            RegistrosAlterar alterarRegistro = new RegistrosAlterar(menu, Codigo);
            abrirMDI(alterarRegistro.getFondo());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:
        if (TabelaProduto.getSelectedRowCount() >= 1) {
            int deleteItem = JOptionPane.showConfirmDialog(null, "Deseja mesmo Excluir Produto",
                    "Warning", JOptionPane.YES_NO_OPTION);
            if (deleteItem == JOptionPane.YES_OPTION) {
                Produto p = new Produto();
                p.setId(Integer.parseInt(TabelaProduto.getValueAt(TabelaProduto.getSelectedRow(), 0).toString()));
                try {
                    produtoDAO.deletarProduto(p);
                    Content panel = new Content(menu);
                    menu.abrirMDI(panel.getFondo());
                } catch (Exception ex) {
                    Logger.getLogger(Content.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }//GEN-LAST:event_btnDeletarActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Impressão Padrão");
        MessageFormat footer = new MessageFormat("Página {0, number, integer}");
        try {
          
            TabelaProduto.print(JTable.PrintMode.NORMAL);
        } catch (PrinterException e) {
            System.err.format("Impressão não encontrada", e.getMessage());
        }
    }//GEN-LAST:event_myButton2ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TabelaProduto.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
    }//GEN-LAST:event_jLabel1MouseClicked

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Content.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Content.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Content.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Content.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Componentes.Table TabelaProduto;
    private Componentes.MyButton btnCadastrar;
    private Componentes.MyButton btnDeletar;
    private Componentes.MyButton btnEditar;
    private javax.swing.JPanel conteudo;
    private com.raven.chart.CurveChart curveChart1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private Componentes.MyButton myButton2;
    private Componentes.MyButton myButton3;
    private javax.swing.JPanel pnlPesquisa;
    private javax.swing.JPanel pnlPesquisa1;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
